
services:

 redis:
      image: redis:8.0-alpine
      container_name: redis-cache
      restart: unless-stopped
      command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
      ports:
        - "6379:6379"
      volumes:
        - redis-data:/data
      networks:
        - app-network

volumes:
  redis-data:
    name: redis-cache-data
    driver: local

networks:
  app-network:
    driver: bridge 