
services:
  complaints-management-db:
    image: postgres:15-alpine
    container_name: complaints-management-db
    env_file: .env
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - app-network
    volumes:
     - pgdata:/var/lib/postgresql/data

  redis:
      image: redis:8.0-alpine
      container_name: redis-cache
      restart: unless-stopped
      command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
      ports:
        - "6379:6379"
      volumes:
        - redis-data:/data
      networks:
        - app-network

  complaints-management:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: complaints-management
    ports:
      - "8000:8000"
  
    networks:
      - app-network
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  pgdata:
    name: complaints-management-db-data
    driver: local
  redis-data:
    name: redis-cache-data
    driver: local

networks:
  app-network:
    driver: bridge 