
@url = https://resolveit.onrender.com/api


### ===== users =====
POST {{url}}/users
Content-Type: application/json

{
    "full_name": "De Valentine",
    "username": "Val",
    "email": "deletethisuser9@gmail.com",
    "phone_number": "+254781234567",
    "password": "@West254."
}



### delete user
DELETE {{url}}/users/551500b3-dcea-4f32-bd52-56326cd7d2ad